### ISSUE TITLE
Select custom fonts

### ISSUE THREAD

**Issue by KidA001** [DannyBen/victor#16]
Let's say I want to load a custom font. I define this in the CSS/Style. How/where are these fonts loaded from?

**Comment by DannyBen** [comment]
Can you paste your example code?

**Comment by DannyBen** [comment]
See [this example](https://github.com/DannyBen/victor/tree/master/examples#12-custom-fonts)

This is not yet in the published gem, will publish soon.

In a nutshell, you can now do this:

```ruby
  css['@import'] = [
    "url('https://fonts.googleapis.com/css?family=Audiowide')",
    "url('https://fonts.googleapis.com/css?family=Pacifico')"
  ]
```

to add one or more `@import` statements.

I have added a way to add `@import` statements to the CSS in the SVG.
Note that this is not working in SVGs that are embedded in HTML as far as I can tell, but this is an SVG issue. If you know otherwise, let me know.

**Comment by KidA001** [comment]
@DannyBen dude, you are awesome!

I'm working on an open source project for an organization for the blind. I'm using this gem to help build and draw a map of a selected city, intersection, point of interest...etc, that they can send to a special printer that will emboss and raise streets, and also print the street names in Braille. Your gem has been extremely helpful in building a SVG of the map that we're printing. I was trying to figure out how to add a custom font (i.e. braille) for the street names.

Let me test out your new commit. 

I really appreciate your responsiveness!

**Comment by KidA001** [comment]
Ok, so I'm adding it to the CSS of the SVG object, and I can see that it's putting it in the SVG file that's generated:
```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg width="665" height="794" 
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">

<style type="text/css">
<![CDATA[
  @import url('https://github.com/techvision/brails/raw/master/public/fonts/braille-webfont.woff');
]]>
</style>
```

I can also see that it's added to the 'text' lines in the SVG file
```
<text x="306.2536497801808" y="100" font-size="10" fill="black" text-anchor="start" transform="rotate(-90,306.2536497801808,100)" font-family="Braille Webfont">
Martin Luther King Jr Way
</text>
```

I don't however see the font when I open the file locally or in my browser. Am I referencing it incorrectly?

**Comment by KidA001** [comment]
It looks like your example links to a CSS file that has something like this:
```
@font-face {
  font-family: 'Barrio';
  font-style: normal;
  font-weight: 400;
  src: local('Barrio Regular'), local('Barrio-Regular'), url(https://fonts.gstatic.com/s/barrio/v1/pvOQbqpnNzX-zOd8UtNFXn-_kf6ByYO6CLYdB4HQE-Y.woff2) format('woff2');
  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}
```

Similar to adding `@import` to the SVG object, is there a way I can add `@font-face` data?

**Comment by DannyBen** [comment]
Great to hear, and glad I can help!

Don't hesitate to post here (or open a new issue) if you have problem.

A few notes:

1. Remember that Victor is here to help you generate SVG in a rubi-esque way - so sometimes it helps to create (or update) the SVG output manually, to first see that you get the result you want (and that you understand the SVG syntax you need), and only then convert it to a Ruby code. This will help you distinguish between SVG issues and Victor issues (or in your case, CSS issues).
2. Although I aim to make it so you can do everything directly from Ruby, in cases that it doesn't work, or doesn't make sense to you - you can always use a different SVG template. So for example, if Victor was not supporting the `@import` statement (as it was in the previous version), you could have simply added it to a template file. See [this section in the readme](https://github.com/DannyBen/victor#svg-templates) if it interests you.
3. It looks like you got it right (I also saw your per-edit comments in my mail) - the `@import` statement in CSS is intended to import another CSS file. If you want to define fonts yourself, you use the `@font-face` statement.
4. Although the code your wrote should be fine, Victor lets you make it feel like a little more natural. The below should also work:

```ruby
svg.css['@font-face'] = {
  font_family:   'Braille',
  font_style:    'normal',
  font_weight:   400,
  src:           "local('Braille'), url(braille-webfont.woff) format('woff2')",
  unicode_range: "U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215"
}




```

This works, since Victor translates underscores in key names, to hyphens.

Hope this helps.

**Comment by KidA001** [comment]
Thanks a ton, appreciate the responsiveness. I'll share the repo for the project once it's public and open-sourced :)
