### ISSUE TITLE
how to import css from external file

### ISSUE THREAD

**Issue by Rashidwi** [DannyBen/victor#55]
Hi,

I've tried all sorts of ideas with no luck.  

How do I import css from an external file  in css format ?

Many thanks 
S

**Comment by DannyBen** [comment]
I am not sure what are you asking. 
Do you want to call an external CSS file from within an SVG?

If so, this is done in SVG by using the `link` directive:

```xml
<svg>
  <link xmlns="http://www.w3.org/1999/xhtml" rel="stylesheet" href="style.css" type="text/css"/>
  # ...
</svg>
```

so, converting this to Ruby, is like any other node. Here is a fully working example:

```ruby
# test.rb
require 'victor'

svg = Victor::SVG.new viewBox: "0 0 100 100"

svg.build do
  link xmlns: "http://www.w3.org/1999/xhtml", rel: "stylesheet",
    href: "style.css", type: "text/css"

  circle id: 'circle', cx: 50, cy: 50, r: 40
end

svg.save "test"
```

```css
/* style.css */
#circle {
  fill: blue;
  stroke: black;
  stroke-width: 10px;
}
```

Then run `ruby test.rb` and you get this SVG:

![image](https://user-images.githubusercontent.com/2405099/98471970-6ed52300-21f8-11eb-862c-0dddfe36fff5.png)


Also - since this is ruby - if you have more than one CSS to import, you can implement a helper function:

```ruby
require 'victor'

svg = Victor::SVG.new viewBox: "0 0 100 100"

def css_link(file)
  link xmlns: "http://www.w3.org/1999/xhtml", rel: "stylesheet",
    href: file, type: "text/css"
end

svg.build do
  css_link "style.css"
  circle id: 'circle', cx: 50, cy: 50, r: 40
end

svg.save "test"
```

**Comment by Rashidwi** [comment]
Thank you, perfect answer!
R

**Comment by DannyBen** [comment]
Cool. I also updated the CSS section in the README to be a little clearer about it.
